### ISSUE TITLE
CLANG-TOOL Puts Everything Into CL-USER

### ISSUE THREAD

**Issue by Shinmera** [drmeister/clasp#138]
It should have its own package.

**Comment by drmeister** [comment]
This is fixed now that clang-tool is part of the clasp-analyzer ASDF system

**Comment by Shinmera** [comment]
On 9390e5f3fa4bad9e11adc00dfbf286e10c4cbda4 it can't find the `clasp-analyzer` system (after loading asdf). Is this expected behaviour?

**Comment by Shinmera** [comment]
On 7fde5b78e98bf1af8e74f3884815a81db9eeec7e the system is still not loadable by default after requiring asdf. Pushing the system manually into ASDF's registry allows loading it, but then errors out:
```
Starting Boehm cclasp 0.3-test-10-463-g7fde5b7 ... loading image... it takes a few seconds
Top level.
> (require :asdf)
*** Do something with proclaim ftype (FTYPE (FUNCTION (T T T &OPTIONAL T) T)
                                        ENSURE-EXPORTED)
*** Do something with proclaim ftype (FTYPE
                                      (FUNCTION
                                       (T &KEY (:DIRECTORY BOOLEAN)
                                        (:WILDEN BOOLEAN)
                                        (:ENSURE-DIRECTORY BOOLEAN))
                                       T)
                                      RESOLVE-LOCATION)
*** Do something with proclaim ftype (FTYPE (FUNCTION (&OPTIONAL T) T)
                                      INITIALIZE-SOURCE-REGISTRY)
("ASDF" "asdf" "UIOP" "uiop")
> (push #p"~/autobuild/clasp-testing/.autobuild/7fde5b78e98bf1af8e74f3884815a81db9eeec7e/src/lisp/clasp-analyzer/" asdf:*central-registry*)   

(#P"/home/linus/autobuild/clasp-testing/.autobuild/7fde5b78e98bf1af8e74f3884815a81db9eeec7e/src/lisp/clasp-analyzer/")
> (require :clasp-analyzer)
;;; Warning: Condition: Undefined function named CLASP-ANALYZER::NO-NODE-FOR-TAG-ERROR-TAG
ASDF could not load clasp-analyzer because
In lisp_errorUnexpectedType ../../src/core/foundation.cc line 161
COMMON-LISP:TYPE-ERROR :initializers (:DATUM COMMON-LISP:NIL :EXPECTED-TYPE COMMON-LISP:BASE-STRING  )
.

Condition of type: SIMPLE-TYPE-ERROR
In lisp_errorUnexpectedType ../../src/core/foundation.cc line 161
COMMON-LISP:TYPE-ERROR :initializers (:DATUM COMMON-LISP:NIL :EXPECTED-TYPE COMMON-LISP:BASE-STRING  )


Available restarts:
(use :r1 to invoke restart 1)

1. (TRY-RECOMPILING) Recompile mps-interface and try loading it again
2. (RETRY) Retry loading FASL for #<CL-SOURCE-FILE "clasp-analyzer" "mps-interface" @0x2aab32b08601>.
3. (ACCEPT) Continue, treating loading FASL for #<CL-SOURCE-FILE "clasp-analyzer" "mps-interface" @0x2aab32b08601> as having been successful.
4. (RETRY) Retry ASDF operation.
5. (CLEAR-CONFIGURATION-AND-RETRY) Retry ASDF operation after resetting the configuration.
6. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at frame[327] TOP-LEVEL.
 File: #P"/home/linus/.cache/shirakumo/autobuild/clasp-testing/.autobuild/7fde5b78e98bf1af8e74f3884815a81db9eeec7e/build/clasp/Contents/Resources/lisp/kernel/lsp/top.lsp" (Position #21029)
>> 
```

**Comment by Shinmera** [comment]
I'll close this due to obscurity.
